name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.25.0
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.0"
          check-latest: true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Check gofumpt formatting
        run: make checkfmt

      - name: Check generated code
        run: make checkgen
